### ISSUE TITLE
感谢作者的分享，我有一些疑惑麻烦作者解答

### ISSUE THREAD

**Issue by kevin666abc** [FenghaoZhu/GMML#2]
作者好，感谢您分享这篇文章的代码，这篇文章对我的启发很大，我有一个疑问：dataset.mat里提供了100个采样信道的数据，请问这100个信道数据是如何获取的？它们采用的是相同的参数吗？因为我运行代码发现，这100个采样信道最终得出的用户速率并不一样。

**Comment by FenghaoZhu** [comment]
采用的相同参数，但是用户随机布撒在一个圆圈内，故这100个采样信道最终得出的用户速率并不一样

**Comment by Gqs0111** [comment]
作者您好，感谢您的分享，这篇文章对我的启发很大。我在运行代码的时候有一个疑问：每item中都会得到一个最大的WSR，一共100次item，我们应该怎么去判断他的最优值呢？
